spc/spc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from admin_notification.views import check_notification_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('user/', include('user.urls')),
    path('check/notification/', check_notification_view, name="check_notifications"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spc/pages/forms.py
from django import forms
from .models import Comment

# الخاص به label مع اخفاء Textarea توجد طريقتين لتعريف
# كل منهما به طريقة CommentUpdateForm و CommentForm النموذجين
# الطريقة الاولى أحدث

class CommentForm(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super(CommentForm, self).__init__(*args, **kwargs)
    #     self.fields['comment'].label = ""

    comment = forms.CharField(label=False, widget=forms.Textarea(attrs={'class':'commentTextArea', 'wrap':'hard', 'placeholder':'اضف تعليقًا...'}))
    class Meta:
        model = Comment
        fields = [ 'comment']
        widgets = {
            # 'comment':forms.Textarea(attrs={'class':'commentTextArea'}),
        }


class CommentUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CommentUpdateForm, self).__init__(*args, **kwargs)
        self.fields['comment'].label = ""

    class Meta:
        model = Comment
        fields = ['comment']
        widgets = {
            'comment':forms.Textarea(attrs={'disabled':'','hidden':'', 'class':'commentTextArea commentUpdateTextArea'}),
        }

spc/templates/forms/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon"
            data-default-icon="{% static 'images/logo.png' %}" 
            type="image/x-icon"
            href="{% static 'images/logo.png' %}">
    <link rel="stylesheet" href="{% static 'css/baseStyle.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/formStyle.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/stondard.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/show_hideText.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/scrollbar.css' %}"/>
    <title>{{ title }} | Smart Pro Centre</title>
</head>
<body>
    <header>
        <div class="header" style="background-image: none; background-color: #f1f1f1; height: fit-content;">
            <div class="content">
                <a href="{% url 'index' %}"><img class="logo" src="{% static 'images/logo.png' %}" alt="SPC logo"></a>
                {% if user.is_authenticated %}
                <div class="btns_contener">
                    <a href="{% url 'profile' %}" class="btn_ btn_info">الملف الشخصي</a>
                    <a href="{% url 'logout' %}" class="btn_ btn_denger btn_not_bg">خروج</a>
                </div>
                {% endif %}
            </div>
        </div>
    </header>

{% block content %}

{% endblock content %}



<script>
    setTimeout(() => {
        const box = document.getElementById('alert_');

        // 👇️ removes element from DOM
        box.style.display = "none";

        // 👇️ hides element (still takes up space on page)
        // box.style.visibility = 'hidden';
    }, 5000); // 👈️ time in milliseconds




    let textValue = document.getElementById("post'{{ post.title }}'").innerHTML;
    var spaces = textValue.split(" ").length - 1;
    const text = document.getElementsByClassName("postBody");
    const show_more_btn = document.getElementsByClassName("show_more");
    
    const textShrink = "display:-webkit-box; -webkit-line-clamp:3; -webkit-box-orient:vertical;";


    function postBody_func(){
        for(i=0; i<text.length; i++){
            if(spaces >= 50){
                text[i].style.cssText = textShrink;
                show_more_btn[0].style.display = "block";
            }
        }
    }

    const buttonPressed = e => {
        id = e.target.id.split("_")
        if(e.target.innerHTML === "شاهد المزيد.."){
            document.getElementById(id[0]).style.cssText = "";
            e.target.innerHTML = "شاهد أقل.";
        }
        else{
            document.getElementById(id[0]).style.cssText = textShrink;
            e.target.innerHTML = "شاهد المزيد..";
        }
    }
    for(let btn of show_more_btn){
        btn.addEventListener("click", buttonPressed);
    }

    // function show_more_func(){
    //     if(show_more_btn[0].innerHTML === "شاهد المزيد.."){
    //         text[0].style.cssText = "";
    //         show_more_btn[0].innerHTML = "شاهد أقل.";
    //     }
    //     else{
    //         text[0].style.cssText = textShrink;
    //         show_more_btn[0].innerHTML = "شاهد المزيد..";
    //     }
    // }
    
    window.onload = postBody_func();
    
</script>

</body>
</html>

spc/templates/forms/commentUpdateForm.html
{% extends 'forms/base.html' %}

{% block content %}

{% include 'another/message.html' %}

<div class="login main">
    <form method="POST" class="loginForm signupForm">
        <h2 class="loginTitle">تعديل التّعليق</h2>
        <div class="inLoginForm inSignupForm">
            {% csrf_token %}
            <input type="text" name="id" value="{{ usercomment.id }}" hidden>
            {{ commentUpdateForm }}
            <textarea name="comment" cols="40" rows="10" class="commentTextArea commentUpdateTextArea" required="" id="id_comment">{{ currentComment }}</textarea>
            <input type="submit" value="تعديل التّعليق" class="btn_ loginBtn">
        </div>
    </form>
</div>

{% endblock content %}

spc/templates/forms/concernsForm.html
{% extends 'forms/base.html' %}

{% block content %}

{% include 'another/message.html' %}

<div class="login main">
    <form method="POST" class="loginForm signupForm">
        <!-- <h2 class="loginTitle">إنشغالك</h2> -->
        {% csrf_token %}
        {{ concernsForm }}
        <input type="submit" value="إرسال" class="btn_ loginBtn">
    </form>
</div>
{% endblock content %}

spc/templates/forms/loginForm.html
{% extends 'forms/base.html' %}

{% block content %}

{% include 'another/message.html' %}

<div class="login main">
    <form method="POST" class="loginForm">
        <h2 class="loginTitle">تسجيل الدّخول</h2>
        <div class="inLoginForm">
            {% csrf_token %}
            {{ loginForm }}
            <a href="{% url 'passwordReset' %}">نسيت كلمة المرور؟</a>
            <input type="submit" value="دخول" class="btn_ loginBtn">
            <p class="text-center">إذا لم يكن لديك حساب، <a href="{% url 'signupForm' %}">أنشئ حساب</a>.</p>
        </div>
    </form>
</div>

{% endblock content %}

spc/templates/forms/passwordChange.html
{% extends 'forms/base.html' %}

{% block content %}

{% include 'another/message.html' %}

<div class="login main">
    <form method="POST" class="loginForm signupForm">
        <h2 class="loginTitle">تغيير كلمة المرور</h2>
        <div class="inLoginForm inSignupForm">
            {% csrf_token %}
            {{ passwordChange }}
            <input type="submit" value="تغيير" class="btn_ loginBtn">
        </div>
    </form>
</div>

{% endblock content %}

spc/templates/forms/passwordReset.html
{% extends 'forms/base.html' %}

{% block content %}

{% include 'another/message.html' %}

<div class="login main">
    <form method="POST" class="loginForm signupForm">
        <h2 class="loginTitle">استعادة كلمة المرور</h2>
        <div class="inLoginForm inSignupForm">
            {% csrf_token %}
            {{ passwordReset }}
            <input type="submit" value="ارسل" class="btn_ loginBtn">
        </div>
    </form>
</div>

{% endblock content %}

spc/templates/forms/passwordResetConfirm.html
{% extends 'forms/base.html' %}

{% block content %}

{% include 'another/message.html' %}

<div class="login main">
    <form method="POST" class="loginForm signupForm">
        <h2 class="loginTitle">استعادة كلمة المرور</h2>
        <div class="inLoginForm inSignupForm">
            {% csrf_token %}
            {{ passwordResetConfirm }}
            <input type="submit" value="ارسل" class="btn_ loginBtn">
        </div>
    </form>
</div>

{% endblock content %}

spc/templates/forms/profileUpdate.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/baseStyle.css' %}"/>
<link rel="stylesheet" href="{% static 'css/formStyle.css' %}"/>
<div class="main">
    <header>
        <div class="header" style="background-image: none; background-color: #f1f1f1; height: fit-content;">
            <div class="content">
                <a href="{% url 'index' %}"><img class="logo" src="{% static 'images/logo.png' %}" alt="SPC logo"></a>
                {% if user.is_authenticated %}
                <div class="btns_contener">
                    <a href="{% url 'logout' %}" class="btn_ btn_denger btn_not_bg">خروج</a>
                </div>
                {% endif %}
            </div>
        </div>
    </header>

    {% include 'another/message.html' %}

    {% if user.is_authenticated %}
    <div class="pUContent">
        <form method="POST" enctype="multipart/form-data" aria-multiselectable="true" class="loginForm signupForm pUForm">
            <div class="card imgCard">
                <label for="fileInput" class="fileInput">
                    <img src="{{ profile.image.url }}" alt="{{ user.username }}">
                </label>
            </div>
            {% csrf_token %}
            {{ userUpdateForm }}
            {{ profileUpdateForm }}
            <a href="{% url 'passwordChange' %}" class="radioInput">تغيير كلمة المرور</a>
            <input type="submit" value="حفظ التّغييرات" class="btn_ loginBtn">
        </form>
    </div>
</div>
{% endif %}
{% endblock content %}

spc/templates/forms/signupForm.html
{% extends 'forms/base.html' %}

{% block content %}

{% include 'another/message.html' %}

<div class="login main">
    <form method="POST" class="loginForm signupForm">
        <h2 class="loginTitle">إنشاء حساب</h2>
        <div class="inLoginForm inSignupForm">
            {% csrf_token %}
            {{ signupForm }}
            <input type="submit" value="تسجيل" class='btn_ loginBtn'>
            <p class="text-center signupText">إذا كان لديك حساب بالفعل، <a href="{% url 'loginForm' %}">سجّل الدّخول</a> بدلًا من ذلك.</p>
        </div>
    </form>
</div>

{% endblock content %}