spc/spc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from admin_notification.views import check_notification_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('user/', include('user.urls')),
    path('check/notification/', check_notification_view, name="check_notifications"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spc/pages/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    title = models.CharField(default='منشور عام', max_length=50)
    content = models.TextField()
    dateTime = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-dateTime']

class PostImage(models.Model):
    postID = models.ForeignKey(Post, on_delete=models.CASCADE)
    images = models.FileField(upload_to='postImages/')
 
    def __str__(self):
        return self.postID.title

class Comment(models.Model):
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    postID = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()
    updated = models.BooleanField(default=False)
    dateTime = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.userID.username + ' >> ' + self.postID.title + ' (' + self.comment + ')'

    class Meta:
        ordering = ['-dateTime']

spc/templates/pages/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon"
            data-default-icon="{% static 'images/logo.png' %}" 
            type="image/x-icon"
            href="{% static 'images/logo.png' %}">
    <link rel="stylesheet" href="{% static 'css/baseStyle.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/formStyle.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/stondard.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/show_hideText.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/scrollbar.css' %}"/>
    <title>{{ title }} | Smart Pro Centre</title>
</head>
<body>


{% block content %}

{% endblock content %}


<script>
    setTimeout(() => {
        const box = document.getElementById('alert_');

        // 👇️ removes element from DOM
        box.style.display = "none";

        // 👇️ hides element (still takes up space on page)
        // box.style.visibility = 'hidden';
    }, 5000); // 👈️ time in milliseconds





    const text = document.getElementsByClassName("postBody");
    const show_more_btn = document.getElementsByClassName("show_more");
    
    const textShrink = "display:-webkit-box; -webkit-line-clamp:3; -webkit-box-orient:vertical;";


    function postBody_func(){
        for(i=0; i<text.length; i++){
            var spaces = (text[i].innerHTML).split(" ").length - 1;
            if(spaces >= 50){
                text[i].style.cssText = textShrink;
                show_more_btn[i].style.display = "block";
            }

        }
    }

    const buttonPressed = e => {
        id = e.target.id.split("_")
        if(e.target.innerHTML === "شاهد المزيد.."){
            document.getElementById(id[0]).style.cssText = "";
            e.target.innerHTML = "شاهد أقل.";
        }
        else{
            document.getElementById(id[0]).style.cssText = textShrink;
            e.target.innerHTML = "شاهد المزيد..";
        }
    }
    for(let btn of show_more_btn){
        btn.addEventListener("click", buttonPressed);
    }
    
    window.onload = postBody_func();
    
</script>


</body>
</html>

spc/templates/pages/index.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}

<header>
    <div class="header">
        {% include 'parts/navbar.html' %}
        {% include 'another/message.html' %}

        {% if user.is_authenticated %}
        <a href="{% url 'main' %}" class="joinBtn">أخبارنا</a>
        {% else %}
        <a href="{% url 'main' %}" class="joinBtn">اِنضم لنا</a>
        {% endif %}
        
    </div>
</header>
<main>
    
    {% if about %}
    <section>
        <div class="about">
            <h2 class="title">من نحن؟</h2>
            <div class="content" dir="auto">
                {% for ab in about %}
                <img loading="lazy" class="" src="{{ ab.image.url }}" alt="SPC image">
                <article>{{ ab.text }}</article>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}
    
    {% if services %}
    <section>
        <div class="services">
            <h2 class="title">خدماتنا</h2>
            <div class="content">
                {% for service in services %}
                <div class="card">
                    <img loading="lazy" src="{{ service.image.url }}" alt="Service image">
                    <div class="data">
                        <h3 dir="auto">{{ service.title }}</h3>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}
    
    {% if history %}
    <section>
        <div class="jobs">
            <h2 class="title">إنجازاتنا</h2>
            <div class="content">
                {% for hist in history %}
                <div class="card">
                    <img loading="lazy" src="{{ hist.image.url }}" alt="Job image">
                    <div class="data">
                        <h3 dir="auto">{{ hist.title }}</h3>
                        <p dir="auto">{{ hist.abstract }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}
    
    {% if team %}
    <section>
        <div class="employes">
            <h2 class="title">فريقنا</h2>
            <div class="content">
                {% for emp in team %}
                <div class="card">
                    <img loading="lazy" src="{{ emp.image.url }}" alt="Employe image">
                    <div class="data">
                        <h3 dir="auto">{{ emp.emp_name }}</h3>
                        <p dir="auto">{{ emp.job_position }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}
    
</main>

{% include 'parts/map.html' %}
{% include 'parts/footer.html' %}
{% endblock content %}

spc/templates/pages/logout.html
{% extends 'forms/base.html' %}

{% block content %}

    {% if not user.is_authenticated %}
    {% include 'another/message.html' %}

    <div class="logout">
        <a href="{% url 'loginForm' %}" class="">سجّل الدخول مجدّداً</a>
    </div>

    {% endif %}
{% endblock content %}

spc/templates/pages/main.html
{% extends 'pages/base.html' %}
{% load static %}
{% block content %}


<header>
    <div class="header">
        {% include 'parts/navbar.html' %}
        {% include 'another/message.html' %}

        {% if not user.is_authenticated %}
        <div class="margin_auto btns_contener mainHeaderBtns">
            <a href="{% url 'loginForm' %}" class="mainHeaderBtn">تسجيل الدّخول</a>
            <a href="{% url 'signupForm' %}" class="mainHeaderBtn">إنشاء حساب</a>
        </div>
        {% else %}
        <div class="header_text_box margin_auto">
            <span class="header_text">
                تابع آخر أخبارنا...
            </span>
        </div>
    </div>
</header>

<main>
    <div class="posts" id="posts">
        <div class="">
            {% for post in posts %}
                <div class="post">
                    
                    <span class="post_title">
                        <img src="/static/images/logo.png" class="post_title_img" alt="SPC Logo">
                        <div class="post_title_data">
                            <span>
                                <img src="/static/images/icons/alertIcons/successIcon01.png" class="authentication_icon" alt="">
                                <bdo dir="ltr">Smart Pro Centre</bdo>
                            </span>
                            <p>
                                <small>
                                    <time datetime="{{ post.dateTime|date:'F d' }} at {{ post.dateTime|date:'h:i A' }}">
                                        <abbr title="{{ post.dateTime|date:'l, F d, Y' }} at {{ post.dateTime|date:'h:i A' }}">
                                            <bdo dir="ltr">{{ post.dateTime|date:'F d' }} at {{ post.dateTime|date:'h:i A' }}</bdo>
                                        </abbr>
                                    </time>
                                </small>
                            </p>
                        </div>
                    </span>
                    <div class="post_show_less">
                        <a href="{% url 'post' post.id post.title %}" >
                        <p dir="auto" class="postBody" id="post'{{ post.title }}'">{{ post.content }}</p></a>
                        <p class="show_more" id="post'{{ post.title }}'_more">شاهد المزيد..</p>
                    </div>

                    <a href="{% url 'post' post.id post.title %}" >
                        <div class="postImages">
                        {% for img in images %}
                            {% if img.postID == post %}
                                <img src="{{ img.images.url }}" class="postImage" alt="Post image">
                            {% endif %}
                        {% endfor %}
                        </div>
                    </a>
                    <form method="POST" class="commentForm">
                        {% csrf_token %}
                        <select name="postID" required="" id="id_postID" hidden>
                            <option value="{{ post.id }}" selected>{{ post.title }}</option>
                        </select>
                        {{commentForm}}
                        <input type="submit" value="تعليق" class="commentSubmitBtn">
                    </form>
                    <details id="comments">
                        <summary class="commentSummaryTag">التعليقات</summary>
                        <div class="">
                            
                            {{ count.initial }}
                            {% for comment in comments %}
                                {% if comment.postID == post and count.count_ < 5 %}
                                    {{ count.increment }}
                                    <div class="comment">
                                        <span class="comment_body">
                                            {% for userProfile in userProfiles %}
                                                {% if userProfile.user == comment.userID %}
                                                <img src="{{ userProfile.image.url }}" class="comment_title_img" alt="User image">
                                                {% endif %}
                                            {% endfor %}
                                            <div class="comment_title_body">
                                                <div class="comment_title_data">
                                                    {{ comment.userID.first_name }} {{ comment.userID.last_name }}
                                                    <details>
                                                        <summary></summary>
                                                        {% if user.is_authenticated and comment.userID.id == user.id %}
                                                        <div class="btns_contener">
                                                            <a href="{% url 'commentUpdateForm' comment.id %}" class="commentBtn">تعديل</a>
                                                            <a href="{% url 'deleteComment' comment.id 'main' %}" class="commentBtn">حذف</a>
                                                        </div>
                                                        {% endif %}
                                                    </details>
                                                </div>
                                                <p dir="auto" class="commentBody">{{ comment.comment }}</p>
                                            </div>
                                        </span>
                                        <small>
                                            <time datetime="{{ comment.dateTime|date:'d-m-Y' }} at {{ comment.dateTime|date:'h:i A' }}">
                                                <abbr title="{{ comment.dateTime|date:'l, F d, Y' }} at {{ comment.dateTime|date:'h:i A' }}">
                                                    <bdo dir="ltr">{{ comment.dateTime|date:'d-m-Y' }} at {{ comment.dateTime|date:'h:i A' }}</bdo>
                                                </abbr>
                                            </time>
                                        </small>
                                        
                                    </div>
                                {% endif %}
                            {% endfor %}
                            {% if count.count_ == 0 %}
                                <h4>لا توجد تعليقات حتى الآن...</h4>
                            {% endif %}

                        </div>
                    </details>
                </div>
            {% empty %}
                <h4>لا توجد منشورات</h4>
            {% endfor %}

            
            {% if posts %}
            <hr>
            {% include 'another/pagination.html' with page=posts %}
            {% endif %}


        </div>
    </div>
</main>
{% include 'parts/map.html' %}
{% include 'parts/footer.html' %}
{% endif %}


{% endblock content %}

spc/templates/pages/post.html
{% extends 'forms/base.html' %}
{% load static %}

{% block content %}

{% include 'another/message.html' %}

<div class="block">
    <div class="detailsPage">
        {% if images %}
            <div class="imgDetailsPageBody">
                <div class="imgDetailsPage">
                    {% for img in images %}
                        {% if images.has_next %}
                            <a href="?page2={{ images.next_page_number }}" class="nextFlesh"><span class="nextFleshIcon">&#10151;</span></a>
                        {% endif %}
                        <img src="{{ img.images.url }}" alt="Post image">
                        {% if images.has_previous %}
                            <a href="?page2={{ images.previous_page_number }}" class="preFlesh"><span class="preFleshIcon">&#10151;</span></a>
                        {% endif %}
                        
                    {% endfor %}
                </div>
            </div>
        {% else %}
        <style>
            @media (max-width : 1000px) {
                .dataDetailsPageBody {
                    width: 100vw;
                    height: 100%;
                    text-align: justify;
                }
            }
        </style>
        {% endif %}

        <div class="dataDetailsPageBody">
            <div class="">
                <span class="post_title ">
                    <img src="/static/images/logo.png" class="post_title_img" alt="SPC Logo">
                    <div class="post_title_data">
                        <span>
                            <img src="/static/images/icons/alertIcons/successIcon01.png" class="authentication_icon" alt="">
                            <bdo dir="ltr">Smart Pro Centre</bdo>
                        </span>
                        <p>
                            <small>
                                <time datetime="{{ post.dateTime|date:'F d' }} at {{ post.dateTime|date:'h:i A' }}">
                                    <abbr title="{{ post.dateTime|date:'l, F d, Y' }} at {{ post.dateTime|date:'h:i A' }}">
                                        <bdo dir="ltr">{{ post.dateTime|date:'F d' }} at {{ post.dateTime|date:'h:i A' }}</bdo>
                                    </abbr>
                                </time>
                            </small>
                        </p>
                    </div>
                </span>
                
                <div class="post_show_less">
                    <p dir="auto" class="postBody" id="post'{{ post.title }}'">{{ post.content }}</p>
                    <p class="show_more" id="post'{{ post.title }}'_more">شاهد المزيد..</p>
                </div>
                    
                
                <form method="POST" class="commentForm">
                    {% csrf_token %}
                    <select name="postID" required="" id="id_postID" hidden>
                        <option value="{{ post.id }}" selected>{{ post.title }}</option>
                    </select>
                    {{commentForm}}
                    <input type="submit" value="تعليق" class="commentSubmitBtn">
                </form>
            
                <div class="" id="comments" >
                    {% for comment in comments %}
                    <div class="comment">
                        <span class="comment_body">
                            {% for userProfile in userProfiles %}
                                {% if userProfile.user == comment.userID %}
                                <img src="{{ userProfile.image.url }}" class="comment_title_img" alt="User image">
                                {% endif %}
                            {% endfor %}
                            <div class="comment_title_body">
                                <div class="comment_title_data">
                                    {{ comment.userID.first_name }} {{ comment.userID.last_name }}
                                    <details>
                                        <summary></summary>
                                        {% if user.is_authenticated and comment.userID.id == user.id %}
                                        <div class="btns_contener">
                                            <a href="{% url 'commentUpdateForm' comment.id %}" class="commentBtn">تعديل</a>
                                            <a href="{% url 'deleteComment' comment.id 'post' %}" class="commentBtn">حذف</a>
                                        </div>
                                        {% endif %}
                                    </details>
                                </div>
                                <p dir="auto" class="commentBody">{{ comment.comment }}</p>
                            </div>
                        </span>
                        <small>
                            <time datetime="{{ comment.dateTime|date:'d-m-Y' }} at {{ comment.dateTime|date:'h:i A' }}">
                                <abbr title="{{ comment.dateTime|date:'l, F d, Y' }} at {{ comment.dateTime|date:'h:i A' }}">
                                    <bdo dir="ltr">{{ comment.dateTime|date:'d-m-Y' }} at {{ comment.dateTime|date:'h:i A' }}</bdo>
                                </abbr>
                            </time>
                        </small>
                        
                    </div>
                    {% empty %}
                        <h4>لا توجد تعليقات حتى الآن...</h4>
                    {% endfor %}
        
                    {% if comments %}
                    {% include 'another/commentsPagination.html' with page=comments %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

        

</div>

{% endblock content %}

spc/templates/pages/profile.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}
<header>
    <div class="header" style="background-image: none; background-color: #f1f1f1; height: fit-content;">
        <div class="content">
            <a href="{% url 'index' %}"><img class="logo" src="{% static 'images/logo.png' %}" alt="SPC logo"></a>
            {% if user.is_authenticated %}
            <div class="btns_contener">
                <a href="{% url 'profileUpdate' %}" class="btn_ btn_info">تعديل</a>
                <a href="{% url 'logout' %}" class="btn_ btn_denger btn_not_bg">خروج</a>

            </div>
            {% endif %}
        </div>
    </div>
</header>

{% include 'another/message.html' %}

{% if user.is_authenticated %}
<main class="bgProfile">
    <section>
        <div class="content data_profile_content">
            <div class="card col1">
                <img src="{{ profile.image.url }}" alt="{{ user.username }}">
                <div class="data">
                    <h3>{{ user.username }}</h3>
                </div>
            </div>
            <div class="col2">
                <div class="line">
                    <span>الاِسم الكامل: </span>
                    <span>{{ user.first_name }} {{ user.last_name }}</span>
                </div>
                <div class="line">
                    <span>البريد الإلكتروني: </span>
                    <span>{{ user.email }}</span>
                </div>
                <div class="line">
                    <span>الجنس: </span>
                    <span>{{ profile.gender }}</span>
                </div>
                <div class="line">
                    <span>رقم الهاتف: </span>
                    <span>{{ profile.phoneNumber }}</span>
                </div>
                <div class="line">
                    <span>العنوان: </span>
                    <span>{{ profile.address }}</span>
                </div>
            </div>
        </div>


        <div class="comment_profile_content" id="comments" >
            <h4 class="profile_action_title">نشاطك على المنصّة</h4>
            {% for usercomment in userComments %}
            <div class="post profileComment">

                <span class="post_title">
                    <div class="post_title_data">
                        <p>
                            علّقت على 
                            <a href="{% url 'post' usercomment.postID.id usercomment.postID.title %}" dir="auto" >
                                {{ usercomment.postID.title }}
                            </a>
                        </p>
                        <small>
                            <time datetime="{{ usercomment.dateTime|date:'d-m-Y' }} at {{ usercomment.dateTime|date:'h:i A' }}">
                                <abbr title="{{ usercomment.dateTime|date:'l, F d, Y' }} at {{ usercomment.dateTime|date:'h:i A' }}">
                                    <bdo dir="ltr">{{ usercomment.dateTime|date:'d-m-Y' }} at {{ usercomment.dateTime|date:'h:i A' }}</bdo>
                                </abbr>
                            </time>
                        </small>
                    </div>
                </span>

                <div class="comment">
                    <span class="comment_body">
                        <img src="{{ profile.image.url }}" class="comment_title_img" alt="{{ user.username }}">
                        <div class="comment_title_body">
                            <div class="comment_title_data">
                                <bdo dir="auto">{{ profile.user.first_name }} {{ profile.user.last_name }}</bdo>
                                <details>
                                    <summary></summary>
                                    <div class="btns_contener">
                                        <a href="{% url 'commentUpdateForm' usercomment.id %}" class="commentBtn">تعديل</a>
                                        <a href="{% url 'deleteComment' usercomment.id 'profile' %}" class="commentBtn">حذف</a>
                                    </div>
                                </details>
                            </div>
                            <p dir="auto" class="commentBody">{{ usercomment.comment }}</p>
                        </div>
                    </span>
                </div>
            </div>
            {% empty %}
            <h4>لا توجد تعليقات من طرفك</h4>
            {% endfor %}

            {% if userComments %}
            {% include 'another/commentsPagination.html' with page=userComments %}
            {% endif %}
        </div>
    </section>
</main>
{% endif %}
{% endblock content %}